S = input()
a=[-1 for i in range(26)]
for i in range(0,len(S),1):
    if(S[i]=='a'):
        if(a[0]==-1):
            a[0] = i
    elif(S[i]=='b'):
        if(a[1]==-1):
            a[1]=i
    elif(S[i]=='c'):
        if(a[2]==-1):
            a[2]=i
    elif(S[i]=='d'):
        if(a[3]==-1):
            a[3]=i
    elif(S[i]=='e'):
        if(a[4]==-1):
            a[4]=i
    elif(S[i]=='f'):
        if(a[5]==-1):
            a[5]=i
    elif(S[i]=='g'):
        if(a[6]==-1):
            a[6]=i
    elif(S[i]=='h'):
        if(a[7]==-1):
            a[7]=i
    elif(S[i]=='i'):
        if(a[8]==-1):
            a[8]=i
    elif(S[i]=='j'):
        if(a[9]==-1):
            a[9]=i
    elif(S[i]=='k'):
        if(a[10]==-1):
            a[10]=i
    elif(S[i]=='l'):
        if(a[11]==-1):
            a[11]=i
    elif(S[i]=='m'):
        if(a[12]==-1):
            a[12]=i
    elif(S[i]=='n'):
        if(a[13]==-1):
            a[13]=i
    elif(S[i]=='o'):
        if(a[14]==-1):
            a[14]=i
    elif(S[i]=='p'):
        if(a[15]==-1):
            a[15]=i
    elif(S[i]=='q'):
        if(a[16]==-1):
            a[16]=i
    elif(S[i]=='r'):
        if(a[17]==-1):
            a[17]=i
    elif(S[i]=='s'):
        if(a[18]==-1):
            a[18]=i
    elif(S[i]=='t'):
        if(a[19]==-1):
            a[19]=i
    elif(S[i]=='u'):
        if(a[20]==-1):
            a[20]=i
    elif(S[i]=='v'):
        if(a[21]==-1):
            a[21]=i
    elif(S[i]=='w'):
        if(a[22]==-1):
            a[22]=i
    elif(S[i]=='x'):
        if(a[23]==-1):
            a[23]=i
    elif(S[i]=='y'):
        if(a[24]==-1):
            a[24]=i
    elif(S[i]=='z'):
        if(a[25]==-1):
            a[25]=i
for i in a:
    print(i,end=" ")